export {default as Main} from './Main'
export {default as Header} from './Header'
export {default as AllPuppies} from './AllPuppies'
export {default as Searchbar} from './Searchbar'
export {default as Puppy} from './Puppy'
